- name: Deploy Site
  hosts: all  # Replace with your target hosts or group name
  gather_facts: yes

  vars:
    site_name: "test-2"

  tasks:

    - name: "Access Site Variables"
      set_fact:
        site: "{{ hostvars[inventory_hostname]['sites'][{{site_name}}] }}"
        repo_name: "{{site.repo_name}}"
        repo_host: "{{site.repo_host}}"
        repo_url: "{{site.repo_url}}"
        branch: "{{site.branch}}"
        repo_dir: "{{site.repo_dir}}"
        work_tree_dir: "{{site.work_tree_dir}}"
        php_executable: "php{{ site.php_version | replace('.', '') }}"

    - include_tasks: tasks/git-update.yml

    - name: Define JSON object
      set_fact:
        json_obj:
          bitbucket-oauth:
            bitbucket.org:
              consumer-key: "{{ bitbucket_consumer_key }}"
              consumer-secret: "{{ bitbucket_consumer_secret }}"
      when: dir_stat.stat.exists

    - name: Convert JSON object to string
      set_fact:
        json_string: "{{ json_obj | to_json }}"
      when: dir_stat.stat.exists

    - name: Composer install
      community.general.composer:
        command: install
        working_dir: "{{ work_tree_dir }}"
        executable: /opt/remi/{{ php_executable }}/root/usr/bin/php
        composer_executable: /usr/local/bin/composer
      environment:
        COMPOSER_HOME: /var/www/composer/
        COMPOSER_AUTH: "{{json_string}}"
      when: dir_stat.stat.exists
      become: yes
      become_user: apache