- name: Ensure the .git directory exists
  file:
    path: "{{ repo_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  become: yes

- name: Ensure the work-tree directory exists
  file:
    path: "{{ work_tree_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755
  become: yes

- name: Clone the Git repository if not already cloned
  command: 'git clone --bare git@{{ repo_url }} {{ repo_dir }}'
  args:
    creates: "{{ repo_dir }}/HEAD"
  environment:
    GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=accept-new -i /usr/local/.ssh/id_ed25519_{{ repo_name }}'
  become: yes
  become_user: apache
  register: clone_result

- name: Add fetch refspec to remote.origin.fetch
  git_config:
    name: remote.origin.fetch
    value: '+refs/heads/*:refs/remotes/origin/*'
    scope: local
    repo: "{{ repo_dir }}"
    state: present

- name: Fetch the latest changes from the repository
  command: >
    sudo -u apache bash -c 'GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new -i /usr/local/.ssh/id_ed25519_{{ repo_name }}" git --git-dir="{{ repo_dir }}" fetch origin'
  become: yes

- name: Check out the latest changes to the work-tree directory
  command: 'git --git-dir="{{ repo_dir }}" --work-tree="{{ work_tree_dir }}" checkout -f {{ branch }}'
  become: yes
  become_user: apache
  environment:
    GIT_SSH_COMMAND: 'ssh -i /usr/local/.ssh/id_ed25519_{{ repo_name }}'
  register: checkout_result
  when: clone_result.changed


- name: Revert local changes to the work-tree directory
  command: >
    sudo -u apache bash -c 'GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new -i /usr/local/.ssh/id_ed25519_{{ repo_name }}" git --git-dir="{{ repo_dir }}" --work-tree="{{ work_tree_dir }}" reset --hard'
  become: yes
  when: not clone_result.changed


- name: Pull the most recent updates to the work-tree directory
  command: >
    sudo -u apache bash -c 'GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new -i /usr/local/.ssh/id_ed25519_{{ repo_name }}" git --git-dir="{{ repo_dir }}" --work-tree="{{ work_tree_dir }}" pull'
  become: yes
  when: not clone_result.changed
